#!/bin/bash

# this script needs sudo to run

# this part clears the screen and pulls the repo
# and install it to /etc
clear
git clone https://www.github.com/LeCoqHardi/WolverinePython
sudo mv WolverinePython /etc
sudo chmod +x /etc/WolverinePython/wolverine
sudo chmod +x /etc/WolverinePython/Scripts/*

# this create the executable file
# and put it to /bin/home/theo/Documents/Github/WolverinePython

touch wolverine
echo "#!/bin/bash" >> wolverine
echo "" >> wolverine
echo "exec /etc/WolverinePython/wolverine" >> wolverine
chmod +x wolverine
sudo mv wolverine /bin
